---
version: "3.8"
services:
  movies:
    image: manokmr1998/manoharkmovies:latest
    ports:
      - 81:80
    deploy:
      replicas: 3
  train:
    image: manokmr1998/manoharktrain:latest
    ports:
      - 82:80
    deploy:
      replicas: 3
  recharge:
    image: manokmr1998/manoharkdth:latest
    ports:
      - 83:80
    deploy:
      replicas: 3
  dth:
    image: manokmr1998/manoharkrecharge:latest
    ports:
      - 84:80
    deploy:
      replicas: 3
